
/** CONFIGURATION */

/* Debug mode */
const DEBUG_MODE = true;
const DISABLE_LOGS  = false;

/* Game conf */
const GAME_WIDTH = 320;
const GAME_HEIGHT = 480;
const GAME_STARTING_GRAVITY = 150;
const GAME_ENDING_GRAVITY = 3000;
const GAME_GRAVITY_ACELERATION =  10;
const GAME_FRICTION = 1.1;
const GAME_SCORE_ACELERATION = 5;

/* Trampoline */
const MAX_TRAMPOLINE_QTY = 3;
const TRAMPOLINE_LIFETIME_IN_SECONDS		= 3;
const TRAMPOLINE_BOUNCE_ANIMATION_OFFSET = 30;
const TRAMPOLINE_RESTITUTION = 1.3;
const TRAMPOLINE_PUG_VELOCITY_INCREMENT = 10;
const MINIMUM_TRAMPOLINE_LENGTH = 60;
const MAXIMUM_TRAMPOLINE_LENGTH = 200;

/* Pug */
const MAX_PUGS_QTY = 1;
const PUGS_RESTITUTION = 1.01;
const PUGS_CIRCLE_BODY_SIZE  = 17;
const PUGS_STARTING_WALKING_SPEED = 25;

/* Goals */
const GOALS_QTY = 2;
const GOALS_PLATFORM_HEIGHT = 50;
const GOALS_PLATFORM_WIDTH = 90;
const GOALS_HEIGHT = 10;
const GOALS_WIDTH = 50;

/* Stating platform */
const STARTING_PLATFORM_WIDTH = 70;
const STARTING_PLATFORM_HEIGHT = 30;
const STARTING_PLATFORM_VERTICAL_POSITION = 70;

/* Deathline */
const DEATHLINE_VERTICAL_POSITION_FROM_BOTTOM = 30

/* Walls */
const RIGHT_WALL_WIDTH = 1;
const LEFT_WALL_WIDTH = 1;


/* Screen */
const SCREEN_OFFSET_RIGHT = 0;
const SCREEN_OFFSET_UP = 0;


const BACKGROUND_COLOR = "#77DDEC";
